# Generated by Django 3.2.12 on 2023-06-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcodedata',
            options={'verbose_name_plural': 'QR Scanning Data'},
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='admin_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='check_out',
            field=models.BooleanField(default=False),
        ),
    ]
