# Generated by Django 3.2.12 on 2023-06-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0002_auto_20230608_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodedata',
            name='receiver',
            field=models.CharField(default='Eunbi Yoon', max_length=255),
            preserve_default=False,
        ),
    ]
