# Generated by Django 3.2.12 on 2023-06-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0003_qrcodedata_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcodedata',
            old_name='data',
            new_name='code_data',
        ),
    ]
