# Generated by Django 3.2.12 on 2023-06-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0004_rename_data_qrcodedata_code_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcodedata',
            old_name='created_at',
            new_name='arriving_at',
        ),
    ]
