# Generated by Django 3.2.12 on 2023-06-27 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0006_rename_check_out_qrcodedata_receiver_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodedata',
            name='admin_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='receiver_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
