# Generated by Django 3.2.12 on 2023-06-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0008_auto_20230627_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodedata',
            name='admin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='receiver_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
